package me.troyg.assignment4;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.nio.file.Path;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Scanner;

public class GUI {
    public File inFile;
    public File outFile;
    public Path parentPath;

    public PrintWriter printWriter;
    public int decimalFormat;
    public int columnAmount;
    public int fieldWidth;
    public Scanner scanner;
    public DecimalFormat formatter;
    public String pattern = "0.";

    public static JFrame jFrame;


    public JPanel jPanel;
    private JButton analyzeButton;
    private JFileChooser jFileChooser = new JFileChooser();
    private JButton openButton;
    private JLabel openFileLabel;

    public GUI() {
        openButton.addActionListener(e -> {
            int option = jFileChooser.showOpenDialog(jFrame);
            if (option == JFileChooser.APPROVE_OPTION) {
                inFile = jFileChooser.getSelectedFile();
                parentPath = jFileChooser.getSelectedFile().getParentFile().toPath();

                openFileLabel.setText(inFile.getName());
            }
        });

        analyzeButton.addActionListener(e -> {
            try {
                scanner = new Scanner(inFile);
            } catch (FileNotFoundException e1) {
                e1.printStackTrace();
            }

            outFile = new File(JOptionPane.showInputDialog("Please enter the name of the output file."));
            if (outFile.exists()) {
                JOptionPane.showMessageDialog(null, "The specified output file already exists. Please try again.");
                return;
            }

            decimalFormat = Integer.valueOf(JOptionPane.showInputDialog("Please input the precision. EX: 2"));
            for (int i=0; i < decimalFormat; i++) {
                pattern = pattern + "0";
            }

            columnAmount = Integer.valueOf(JOptionPane.showInputDialog("How many columns do you want?"));

            fieldWidth = Integer.valueOf(JOptionPane.showInputDialog("How big do you want each field?"));



            try { //Creating the file
                printWriter = new PrintWriter(outFile);
            } catch (FileNotFoundException e2) {
                e2.printStackTrace();
            }
            int column = 0;


            while (scanner.hasNext()) {
                float d = scanner.nextFloat();
                formatter = new DecimalFormat();
                formatter.applyPattern(pattern);
                float formattedFloat = Float.valueOf(formatter.format(d));
                if (column == columnAmount) {
                    printWriter.println("");
                    column = 0;
                }

                printWriter.format("%-"+ (fieldWidth-1) + "s ", formattedFloat);
                column++;
            }

            printWriter.close();
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new GridBagLayout());
        jPanel.setMaximumSize(new Dimension(250, 100));
        jPanel.setMinimumSize(new Dimension(250, 100));
        jPanel.setOpaque(false);
        jPanel.setPreferredSize(new Dimension(250, 100));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setMaximumSize(new Dimension(78, 130));
        panel1.setMinimumSize(new Dimension(78, 130));
        panel1.setPreferredSize(new Dimension(40, 30));
        panel1.setRequestFocusEnabled(true);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        jPanel.add(panel1, gbc);
        openButton = new JButton();
        openButton.setText("Open");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 2, 0, 0);
        panel1.add(openButton, gbc);
        analyzeButton = new JButton();
        analyzeButton.setText("Analyze");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 2);
        panel1.add(analyzeButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        jPanel.add(panel2, gbc);
        openFileLabel = new JLabel();
        openFileLabel.setHorizontalAlignment(0);
        openFileLabel.setHorizontalTextPosition(0);
        openFileLabel.setMaximumSize(new Dimension(46, 10));
        openFileLabel.setMinimumSize(new Dimension(46, 10));
        openFileLabel.setPreferredSize(new Dimension(46, 10));
        openFileLabel.setText("Open File");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(openFileLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }

}

/*                if (numSize > fieldWidth) {
                    int removeAmount = numSize - fieldWidth;
                    if (decimalSize < removeAmount) { //Just remove all
                        printWriter.format(Math.round(f) + "\t\t", f);
                    } else {
                        int d = decimalSize - removeAmount;
                        if (d < decimalSize) {
                            printWriter.format("%." + decimalFormat + "f\t\t", f);

                        } else {
                            printWriter.format("%." + d + "f\t\t", f);
                        }
                    }
                } else {
                    printWriter.format("%." + decimalFormat + "f\t\t", f);
                }*/
