package me.troyg.assignment4;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.nio.file.Path;

public class GUI {
    public File inFile;
    public File outFile;
    public Path path;

    public static JFrame jFrame;


    public JPanel jPanel;
    private JButton analyzeButton;
    private JFileChooser jFileChooser = new JFileChooser();
    private JButton openButton;
    private JLabel openFileLabel;

    GUI() {
        openButton.addActionListener(e -> {
            int option = jFileChooser.showOpenDialog(jFrame);
            if (option == JFileChooser.APPROVE_OPTION) {
                openFileLabel.setText(jFileChooser.getSelectedFile().getName());
            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new GridBagLayout());
        jPanel.setMaximumSize(new Dimension(250, 100));
        jPanel.setMinimumSize(new Dimension(250, 100));
        jPanel.setOpaque(false);
        jPanel.setPreferredSize(new Dimension(250, 100));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setMaximumSize(new Dimension(78, 130));
        panel1.setMinimumSize(new Dimension(78, 130));
        panel1.setPreferredSize(new Dimension(40, 30));
        panel1.setRequestFocusEnabled(true);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        jPanel.add(panel1, gbc);
        openButton = new JButton();
        openButton.setText("Open");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 2, 0, 0);
        panel1.add(openButton, gbc);
        analyzeButton = new JButton();
        analyzeButton.setText("Analyze");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 2);
        panel1.add(analyzeButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        jPanel.add(panel2, gbc);
        openFileLabel = new JLabel();
        openFileLabel.setHorizontalAlignment(0);
        openFileLabel.setHorizontalTextPosition(0);
        openFileLabel.setMaximumSize(new Dimension(46, 10));
        openFileLabel.setMinimumSize(new Dimension(46, 10));
        openFileLabel.setPreferredSize(new Dimension(46, 10));
        openFileLabel.setText("Open File");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(openFileLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }

}
